name: Build Binary

on:
  release:
    types:
    - published
  workflow_dispatch:
    inputs: {}

jobs:
  refresh:
    name: build-binary
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.5'

    - name: Download deps
      run: |
        go mod download

    - name: Test
      run: |
        go test ./...

    - name: Build
      run: |
        go build

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["activities-rss"]'
