name: Test

on:
  push:
    branches:
    - '*'
    tags-ignore:
    - '*'

jobs:
  refresh:
    name: test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.5'

    - name: Download deps
      run: |
        go mod download

    - name: Test
      run: |
        go test ./...
